### ISSUE TITLE
关于hook 文件重定向问题请教

### ISSUE THREAD

**Issue by Caij** [uestccokey/EZProtect#1]
遇到一个问题就是破解者hook底层的文件读取，破解的apk内把源文件apk打到包里面，运行时把apk完整性校验映射到原文件apk路径上，这种方式有没有好的反制手段吗。
我看项目源码里面使用fopen的代码，其实fopen的方式可能被hook，映射到一个原文件apk路径上。

**Comment by uestccokey** [comment]
是的，靠单一方案，无法完全避免被破解，只能多管齐下，采用多种检测方案，来增加破解难度，延长破解时间。
